---
title: "Project Proposal"
output: html_notebook
---

## Section 1. Introduction

Sleep is often a point of contention for college students. While most would agree that sleep is important, external factors such as work, studying, and mental health can impact one's sleep schedule - and that's an issue.

Getting enough sleep is a necessary step for maintaining both physical and mental health, but that can often come in conflict with college and adult life. This project hopes to explore a sample of College Students who participated in a study on Sleep Patterns, and understand varying demographics' sleep behavior as well as how sleep correlates with **grades**,**mental health** and **cognitive function**  

## Section 2. Data Analysis Plan

Some questions that I hope to answer include:

- How do different demographics tend to sleep?

- How does sleep correlate with mental health?

- Can sleep have an effect on someone's cognitive function?

- How does poor sleep tend to affect grades?

## Section 3. Data

Dataset provided by [Professor Rei Sanchez-Arias](mailto:rsanchezarias@floridapoly.edu). It can be found here:

<https://github.com/reisanar/datasets/blob/master/SleepStudy.csv>. 

It contains 27 variables and 253 observations, and is distributed in .csv format.

Variables include:

 Variables    |  Description
------------  |----------------------------------------------------------------
`Gender`      | 1 = male, 0 = female
`ClassYear`        | Year in school, 1 = first year, ..., 4 = senior
`LarkOwl` | Early riser of night owl? Lark, Neither, or Owl
`NumEarlyClass`  | Number of classes per week before 9am
`EarlyClass`      | Indicator for any early classes
`GPA`        | Grade point average (0-4 scale)
`ClassesMissed`| Number of classes missed in a semester
`CognitionZscore`  | Z-score on a test of cognitive skills
`PoorSleepQuality`      | Measure of sleep quality (higher values are poorer sleep)
`DepressionScore`        | Measure of degree of depression
`AnxietyScore` | Measure of amount of anxiety
`StressScore`  | Measure amount of stress
`DepressionStatus`      | Coded depression score: normal, moderate, or severe
`AnxietyStatus`        | Coded anxiety score: normal, moderate, or severe
`Stress` | Coded stress score: normal or high
`DASScore`  | Combined score for depression, anxiety and stress
`Happiness`      | Measure of degree of happiness
`AlcoholUse`        | Self-reported: Abstain, Light, Moderate, or Heavy
`Drinks` | Number of alcoholic drinks per week
`WeekdayBed`  | Average weekday bedtime (24.0 = midnight)
`WeekdayRise`      | Average weekday rise time (8.0 = 8am)
`WeekdaySleep`        | Average hours of sleep on weekdays
`WeekendBed`| Average weekend bedtime (24.0 = midnight)
`WeekendRise`  | Average weekend rise time (8.0 = 8am)
`WeekendSleep` | Average weekend bedtime (24.0 = midnight)
`AverageSleep` | Average hours of sleep for all days
`AllNighter`   | Had an all-nighter this semester? 1 = yes, 0 = no

_Data Dictionary provided by Professor Rei Sanchez-Arias [here](https://github.com/reisanar/datasets/blob/master/README.md)_
